name: Run .NET Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore

    - name: Run project
      run: dotnet run 

    - name: Notify success via ntfy
      if: success()
      run: |
        curl -d "✅ .NET build & run succeeded" https://ntfy.sh/my-dotnet-build

    - name: Notify failure via ntfy
      if: failure()
      run: |
        curl -d "❌ .NET build or run failed" https://ntfy.sh/my-dotnet-build

